name: ai_image_generetor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dio:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  image_downloader: ^0.31.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  flutter_launcher_icons: ^0.11.0
  material_design_icons_flutter: ^6.0.7096
  hive: ^2.2.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/red_panda_ia.jpeg
    - assets/images/red_panda_ia_pixar.jpeg
    - assets/images/red_panda_ia_van_gogh.jpeg
    - assets/images/tips_img_01.jpeg
    - assets/images/tips_img_02.jpeg
    - assets/images/tips_img_03.jpeg
    - assets/images/tips_img_04.jpeg
    - assets/images/tips_img_05.jpeg
    - assets/images/tips_img_06.jpeg
    - assets/images/chatgpt_logo.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ai_image_generation_icon.png"